os: linux
dist: bionic

language:
    - c
    
before_install:
    - pip install --user cpp-coveralls
    
addons:
    sonarcloud:
        organization: "brovkinartem"
    token: &SONAR_TOKEN
    
script:
    - qmake 
    - make
    - ./tests/tests
    
after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    - sonar-scanner
    
notifications:
    email: false
